// "use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import Provider from "@/hooks/provider";
// import { NavbarDemo as Navbar } from "@/components/ui/navbar/Navbar";
import NavBar from "@/components/ui/navbar/NavbarChakra";
import { Boxes } from "@/components/ui/background-boxes";

const inter = Inter({ subsets: ["latin"] });

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background  font-sans antialiased flex flex-col justify-center align-center",
          fontSans.variable
        )}
      >
        <Provider>
          {/* <Navbar/> */}
          <NavBar />
          <div className="min-h-screen flex-col items-center justify-center align-center">
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
