// "use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import Provider from "@/hooks/provider";
// import { NavbarDemo as Navbar } from "@/components/ui/navbar/Navbar";
import NavBar from "@/components/ui/navbar/NavbarChakra";
import { Boxes } from "@/components/ui/background-boxes";
import { Toaster } from 'react-hot-toast';


const inter = Inter({ subsets: ["latin"] });

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      
        className={cn(
          "pt-16 min-h-screen bg-background  font-sans antialiased flex flex-col justify-center items-center bg-gradient-to-r from-neutral-50 to-stone-400",
          fontSans.variable
        )}
      >
        <Provider>
          {/* <Navbar/> */}
          <NavBar />
          <div className="flex-grow container mx-auto p-4">
            {children}
          </div>
          <Toaster />

        </Provider>
      </body>
    </html>
  );
}
